name: o4- using action

on: push

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: installing dependences
        run: npm ci
        working-directory: 04-using-action/recat-app
