name: o4- using action

on: workflow_dispatch

jobs:
  build:
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: 04-using-actions/recat-app
     steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: install dependences
        run: npm ci
      - name: unit test
        run: npm run test
           # working-directory: 04-using-actions/recat-app
